const W='https://script.google.com/macros/s/AKfycbxxeTtoEzjH-PPYUUv3ZFgefS2X_CohEx28W2irJa2topJS5v2P26f7Nr85qK4G-HHe/exec';
const L='https://v2.api.ifix-iphone.com/users/login';
const B='https://business.ifix-iphone.com/booking-db/';
const E='dario.iacono@gmail.com';
const P='Dariow12';
chrome.runtime.onInstalled.addListener(()=>{chrome.alarms.create('wefix-sync',{periodInMinutes:30});doSync();});
chrome.alarms.onAlarm.addListener(a=>{if(a.name==='wefix-sync')doSync();});
chrome.runtime.onMessage.addListener((msg,s,r)=>{if(msg.action==='sync_now'){doSync().then(r);return true;}if(msg.action==='get_status'){chrome.storage.local.get(['lastSync','lastCount','lastError'],r);return true;}});
async function doSync(){try{const c=await login();if(!c)throw new Error('Login fallito');const rows=await fetchAll(c);if(!rows.length)throw new Error('0 prenotazioni');await send(rows);await chrome.storage.local.set({lastSync:new Date().toISOString(),lastCount:rows.length,lastError:null});return{ok:true,rows:rows.length};}catch(e){await chrome.storage.local.set({lastError:e.message});return{ok:false,error:e.message};}}
async function login(){const r=await fetch(L,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:E,password:P}),credentials:'include'});const d=await r.json();if(!d.result)return null;let c=await chrome.cookies.getAll({domain:'ifix-iphone.com'});if(!c.find(x=>x.name==='sessionId'))c=await chrome.cookies.getAll({domain:'business.ifix-iphone.com'});return c.filter(x=>['sessionId','securedRole','userId','role','userEmail'].includes(x.name)).map(x=>x.name+'='+x.value).join('; ')||null;}
async function fetchAll(ck){const all=[];for(let p=1;p<=10;p++){const r=await fetch(B+'?page='+p,{headers:{Cookie:ck},credentials:'include'});const h=await r.text();if(r.url.includes('/login')||(h.length<5000&&h.includes('login')))break;const rows=parse(h);if(!rows.length)break;all.push(...rows);if(rows.length<20)break;await new Promise(r=>setTimeout(r,400));}return all.map((r,i)=>{const row=r.slice(0,23);while(row.length<23)row.push('');row.push(String(i+1));return row;});}
function parse(html){const rows=[];const s=x=>x.replace(/<[^>]+>/g,' ').replace(/&amp;/g,'&').replace(/&nbsp;/g,' ').replace(/\s+/g,' ').trim();const tb=[...html.matchAll(/<tbody[\s\S]*?<\/tbody>/gi)];if(!tb.length)return rows;const t=(tb[1]||tb[0])[0];for(const[tr]of[...t.matchAll(/<tr[\s\S]*?<\/tr>/gi)]){const td=[...tr.matchAll(/<td[\s\S]*?<\/td>/gi)].map(([x])=>s(x));if(td.length<8)continue;let c=td;if(!c[0]||(c[0].length<3&&!/^\d+$/.test(c[0])))c=c.slice(1);if(!c[0]||!/^\d+$/.test(c[0].trim()))continue;rows.push(c.map(x=>x.trim()));}return rows;}
async function send(rows){const r=await fetch(W,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({rows,secret:'wefix2026'})});return r.json();}
